# Generated by Django 2.2.4 on 2019-08-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='tours.Tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='pais',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zonaLlegada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_llegada', to='tours.Zona'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zonaSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_salida', to='tours.Zona'),
        ),
    ]
